### ISSUE TITLE
Correct way to handle such a scenario (for token replacement)

### ISSUE THREAD

**Issue by advapiIT** [colindembovsky/cols-agent-tasks#100]
Excuse me if I write here but I've found no better place to ask about token replacement.I've followed your guide [here](https://colinsalmcorner.com/post/end-to-end-walkthrough-deploying-web-applications-using-team-build-and-release-management).

In the test environment, I've set everything correctly. Now I've to manage the deploy of the production code. I've a quite strange scenario where I've 3 different nodes each one with a setting that changed based on the node number (We've 3 frontends, 3 backends and they're associated vertically (They make a perverse use of session so we can't right now have to point to a symbolic name and have a balancer for backend).

So in this current scenario, I've to substitute a WCF endpoint and an app setting. Have I to set 3 different publish profile and execute a deploy on each or is there a better way to handle this?

Thanks in advance
Paolo

p.s. I'm on VTFS 2015

**Comment by colindembovsky** [comment]
Hi @advapiIT - if you create a single tokenized package (so you have the webdeploy zip file and the `SetParameters.xml` file) then you'd have to do the token replacement/deployment for each node. If you're using a single agent, you'll have to copy the tokenized file (so that you don't overwrite it) to  separate folders (one for each node). and do the replace/deploy from there to each corresponding node.
