### ISSUE TITLE
How to detect changed assemblies

### ISSUE THREAD

**Issue by anujgeek** [colindembovsky/cols-agent-tasks#129]
This is not an issue, but a question or a suggestion.
Is there a way we can upgrade an assembly's version number only if the assembly has been updated since the last build/release?
We have a VS .sln file consisting of a large number of cs and vb projects. The solution is built/deployed using build/release pipelines on Azure Devops service. I'd like to achieve two things:
1. Only build projects (and dependent projects) which have their source code updated
2. Only upgrade assembly version for those projects.
I appreciate any help you can provide with this.

**Comment by colindembovsky** [comment]
Hi @anujgeek - what is your unit of deployment? Is it an individual project (dll) or the entire application? If it's the entire application, then you should update the assembly version each build. If it's component-level, then I suggest breaking the solution up so that you have a boundary at "deployable unit" - that way you increment the assembly version each time you have a potentially deployable unit of change. You may want to break off common code into packages and use Package Management to opt-in to updates. That way common code is still bumped every build and published to the package feed.

I honestly don't see a good reason to NOT increment the assembly version every time you build. I also advocate strongly for matching assembly version to build number for consistency and traceability.

**Comment by anujgeek** [comment]
Hi @colindembovsky, the deployment unit for us is the whole solution, consisting or around 100 projects. Breaking the deployment unit is not possible, as we have too many inter-dependent projects dependencies. We currently manually maintain such a mapping, and I now plan to do this by examining the project files for dependency references. Any suggestion you can provide for a use case like ours?
