### ISSUE TITLE
Cannot read property toLowerCase of undefined

### ISSUE THREAD

**Issue by vikramdadwal** [colindembovsky/cols-agent-tasks#133]
My task throwing error:

**Error**

![image](https://user-images.githubusercontent.com/10174566/66149220-7246b580-e5c7-11e9-81d7-319bbf16add7.png)

**Build Definition**

![image](https://user-images.githubusercontent.com/10174566/66149390-da959700-e5c7-11e9-8b92-48abcc1550d0.png)

**Variable**

![image](https://user-images.githubusercontent.com/10174566/66149411-e4b79580-e5c7-11e9-8af0-2064b1d7e418.png)

**Comment by colindembovsky** [comment]
Hi @vikramdadwal - the Token Regex is supposed to be a _pattern_ for the replacement. So you should use the default `__(\w+)__` for Token Regex. This means "find any word pre- and post-fixed with `__` and replace that token with the value of the variable with the token name". I think the error you're seeing is coming up because of the incorrect regex pattern.

**Comment by vikramdadwal** [comment]
Thanks @colindembovsky . This is working now.
