### ISSUE TITLE
AssemblyVersion: any chance of specifying alternate env variable?

### ISSUE THREAD

**Issue by mrbelk** [colindembovsky/cols-agent-tasks#18]
Because of the way the versionCode works on Android and how it's disconnected from versionName, and because of the way the $(rev:.r) variable works in VSTS, it's very difficult to use a $(Build.BuildNumber) that is somehow based on a scheme that could change daily (like 2016.06.08.r), which would reset "r" when the date changes.

So, is there any chance of being able to specify an alternate environment variable from which to draw this versionCode value? even if we were to maintain the version numbers and names in the project, and just use a "static" $(Build.BuildNumber), eventually the build numbers would become meaningless because they would just be 1.0.0.1, 1.0.0.2, 1.0.0.3 with very little context.

Am I totally off base?

Thanks.

**Comment by colindembovsky** [comment]
hey @mrbelk - not sure what your ask is. Do you want to specify your own version numbers instead of taking it from the build?

If so, that kind of defeats the purpose of this task. This task is meant to match the assembly version to the build number. If you don't like the 1.0.0.r format, then I'd suggest that you [create a custom build number](http://blog.ehn.nu/2015/10/generate-custom-build-numbers-in-tfs-build-vnext/) and then use the version assemblies task right after doing whatever it is that you need to do. That way you get a scheme that you're happy with and the version assemblies still works as-is.

Let me know if you were thinking of something else entirely :-)

**Comment by mrbelk** [comment]
I can see how my original post could be confusing.  I love the idea of using the Build number in the versioning of assemblies.

I was more noting that there could be a flaw in the "versionCode" usage of this task because when any part of the BuildNumber changes, the $(rev) property will reset back to one; breaking the "monotonically increasing" requirement of the Android versionCode.  So if you change the build number from 1.0.0$(rev:.r) to say 1.1.0$(rev:.r), then your versionCode will drop back to 1.

I actually wound up writing my own powershell task to synthezise a version code based on the current date.

**Comment by colindembovsky** [comment]
Ah I see what you're getting at. Unfortunately no (clean) way around that.
