### ISSUE TITLE
Version Assemblies: DIfferent versions types & different version source

### ISSUE THREAD

**Issue by nphmuller** [colindembovsky/cols-agent-tasks#21]
Hi!

I'm going to implement some additional functionality in your script and was wondering if you were interested. If you are, I'll make a pull request. It probably does not really fit within the scope of the task, but I figured I could at least ask.

I'm going to add the following things:
-Specify a version source. 
This means that the build task has an extra input field that specifies what version value will be used. Default value can be $(Build.BuildNumber) to make sure the task uses the same values it currently does.
-Different versions for different assembly attributes.
This adds to the previous addition. Instead of a single field, there will be 3: AssemblyVersion, AssemblyFileVersion and AssemblyInformationVersion. Especially handy with libraries, because AssemblyVersion should only be updated for breaking changes and AssemblyFileVersion is updated for every build.

Let me know! :)

**Comment by jstawski** [comment]
I would be very interested in something like this. I would like for this task to be able to change the version of multiple items, not just one. For example, in Android we have to change the versionName and versionCode. So if my versioning schema looks like 1.1.0.15 with the regex `(?:\d+\.\d+\.\d+\.)(\d+)` I would like that to translate to `android:versionName="1.1.0.15" android:versionCode="15"`. If this is already doable, please excuse my ignorance and kindly point me to how to do it.

**Comment by colindembovsky** [comment]
Hi @nphmuller

I'd like to keep the VersionAssemblyTask very simple. If you just add an advanced option (so that it's not initially visible) for version number that defaults to $(Build.BuildNumber) I think that would be fine.

As for the "3 fields" I don't think it's necessary. You can achieve your aim if you hard-code the AssemblyVersion and AssemblyInformationVersion and then specify 9.9.9.9 for the AssemblyVersion in the AssemblyInfo file and then just change the regex to 9\.9\.9\.9. Then only that number will be replaced.

Let me know when you've done the PR for the Version Source!

**Comment by colindembovsky** [comment]
Hi @jstawski 

Perhaps when @nphmuller has a Source Version, you can do 2 passes on the file. The first will replace the 1.1.0.15 using \d+\.\d+\.\d+\.\d+ and the 2nd pass using versionCode="\d+" (you'd have to figure out how to extract the revision number from the full number somehow).

Otherwise in the meantime you can use the ReplaceTokens task and just tokenize the file!

**Comment by jstawski** [comment]
@colindembovsky thanks for the info. I was already running a custom shell script for replacing some text in the manifest file using `sed`, so I just modified that script to do the replacement there.
