### ISSUE TITLE
Escaping special characters in ReplaceTokens Secrets

### ISSUE THREAD

**Issue by joshfitabase** [colindembovsky/cols-agent-tasks#24]
Colin,

Any way to escape the ':' and ';' characters when using Advanced -> Secret Tokens?

Related - does usage of your Secret Tokens feature provide additional security beyond simply not echoing the secrets to logs and masking them in the K:V pair UI? (i.e. does it protect me from more than just eyes over my shoulder / someone with direct access to my VSTS account?)

p.s. sorry for the duplicate issue, I thought maybe this was user error and deleted my first issue on this. (of course, it still may be user error, in which case please correct me!)

**Comment by colindembovsky** [comment]
hey @joshfitabase - not sure what you mean by "additional security"? What else are you looking for other than masking in the logs? By the way, the new (.NET Core) agent that uses vsts-task-lib actually passes the secret variables to the task, so sometime soon I'll remove the property from the frontend (passing it in via K:V pairs was a hack since the current vso-task-lib doesn't pass secret variables to the tasks).

**Comment by joshfitabase** [comment]
@colindembovsky thanks for the quick reply! That's pretty much what I expected. I wasn't sure what else it could be doing for me behind the scenes, but I wanted to cover my bases in case your reply was something like "due to strange quirks in the vsts environment https doesn't get used for that logging data so you really want to obfuscate it"

It still would be nice to have an escape sequence for those characters, but sounds like it isn't a dealbreaker if the only security concern is someone with direct account access (or standing behind me)
