### ISSUE TITLE
Coverage Gate: Cannot read property 'coverageStats' of undefined

### ISSUE THREAD

**Issue by bruhaha1313** [colindembovsky/cols-agent-tasks#41]
I'm trying out the CoverageGate task on VSTS, and I'm getting an error:

##[error]Cannot read property 'coverageStats' of undefined

I've enabled the OAuth token and I have at least two builds with published Code Coverage stats, so I'm not sure what's wrong.

As requested, here is the attached verbose build log:
[1_Build.txt](https://github.com/colindembovsky/cols-agent-tasks/files/699522/1_Build.txt)

**Comment by colindembovsky** [comment]
Hi @bruhaha1313 - looks like you're adding the CoverageGate task at the end of a build. I don't think this will work since the coverage statistics are uploaded to the server asynchronously, so at the point in time you're trying the compare, it looks like the coverage stats are not yet available.

Does your build trigger a release? I usually put this task as the first task in a release that is triggered off the build.

**Comment by bruhaha1313** [comment]
That's very interesting to hear, but it appears you're correct -- I moved the CoverageGate task to run after my Build Publish step to give the asynchronous upload more time to complete, and that fixed it. I never would have guessed it was asynchronous from the build server's output though (the last line of the "Test" step's log says "Published Test Run" and then lists a URL -- I would have guessed that means it's available now, but apparently not).

Thanks for the help!
