### ISSUE TITLE
ReplaceTokens fails with space in path

### ISSUE THREAD

**Issue by pascalberger** [colindembovsky/cols-agent-tasks#6]
Recently the ReplaceTokens task fails if the path contains a space. It worked with version 0.0.3 on the 26th february, but fails today with version 0.0.4.

Error message:
```
2016-03-07T19:33:02.2330283Z ##[error]Could not find file "D:\BuildAgent\_work\d5b03417b\Some Folder\Debug\SomeProject.Web.SetParameters.xml"
```

**Comment by colindembovsky** [comment]
Hi @pascalberger - I can't seem to repro this issue. Can you please set `system.debug` to `true` in your build definition and run the build. Then can you send me the log or just the part of the log for the `ReplaceTokens` task? Then I can dig a little deeper.

FYI I'm using the `vso-task-lib` functions to find the file, and that apparently is returning a list with count != 1, which is why you're seeing this error. However, if I run `node` and import `vso-task-lib` and find a file in a directory with a space in it, it's returning 1 result as expected.

**Comment by jrabarton** [comment]
I'm getting no files to process
![missingfiles](https://cloud.githubusercontent.com/assets/17473449/13675287/cc63fe5c-e6d8-11e5-8f5a-f172c5670d62.png)

does the source path support wildcards and folder recursion?

**Comment by colindembovsky** [comment]
Hi @jrabarton - No, the task requires a specific (fully specified) path. It will allow `$(agent.sourcesdirectory)` or other variables, but the path must be to a single file. Can you tell me why you'd want multiple files or wildcards?

**Comment by jrabarton** [comment]
Our solutions have web and often multiple middleware files, these are in separate projects in the same solution. 

Even if we don't change code in a middleware we still build and release all the projects to keep everything at the same version number for auditing purposes.

**Comment by colindembovsky** [comment]
Hi @jrabarton. I've changed the ReplaceToken task to take in a `sourcePath` and a `filePattern`. That way you can do `minimatch` patterns and replace in multiple files. Let me know how it goes!
