### ISSUE TITLE
Tags textbox doesn't resolve variables

### ISSUE THREAD

**Issue by mrchrisok** [colindembovsky/cols-agent-tasks#65]
Terrific tools Colin!
However, the Tags textbox of the Tag Build task does not recognize variables.  I want to tag builds with the reason for the build. VSTS provides it via $(Build.BuildReason).  However when I input $(Build.BuildReason) in the Tags textbox, the tag set is '$(Build.BuildReason)' instead of the resolved build reason value.  Is this fixable?

**Comment by colindembovsky** [comment]
Hi @mrchrisok - strange, since I use `$(Build.BuildNumber)` and that works. Can you make sure `$(Build.BuildReason)` actually has a value (if you try use a variable expansion and the variable doesn't exist, VSTS just treats it as a string). Are you using this in a Release or in a Build? If in a Release, then `$(Build.BuildReason)` may not evaluate to anything - which would explain your symptoms.
