### ISSUE TITLE
two tokens on the same line

### ISSUE THREAD

**Issue by userjeff3** [colindembovsky/cols-agent-tasks#66]
Should it be possible to tokenize two variables on the same line? On one line I have "<id>APL__app__X__env__</id>". This generates the error: "##[warning]Token [app__X__env] does not have an environment value".

**Comment by colindembovsky** [comment]
Hi @userjeff3 - no, this probably won't work because of the regex. I'd suggest you make a single token like so:
```xml
   <key="conStr" value="__AppEnv__" />
```
Then define three variables in your release:

Variable | Value
--- | ---
App | `MyApp`
Env | `MyEnv`
AppEnv | `APL$(MyApp)_X_$(Env)`

In essence this is using VSTS to combine the 2 vars into a single one that will replace the single token.
